// <auto-generated />
using Coreapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Coreapp.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20201129213822_new")]
    partial class @new
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Coreapp.Models.VehicleMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Abrv")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("VehicleMake");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abrv = "BMW",
                            Name = "Bayerische Motoren Werke AG"
                        },
                        new
                        {
                            Id = 2,
                            Abrv = "Mercedes",
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 3,
                            Abrv = "Ford",
                            Name = "Ford Motor Company"
                        },
                        new
                        {
                            Id = 4,
                            Abrv = "Hyundai",
                            Name = "The Hyundai Motor Company"
                        },
                        new
                        {
                            Id = 5,
                            Abrv = "Mazda",
                            Name = "Mazda Motor Corporation"
                        },
                        new
                        {
                            Id = 6,
                            Abrv = "Porsche",
                            Name = "Porsche AG"
                        },
                        new
                        {
                            Id = 7,
                            Abrv = "Renault",
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 8,
                            Abrv = "Škoda",
                            Name = "Škoda Auto"
                        },
                        new
                        {
                            Id = 9,
                            Abrv = "Audi",
                            Name = "Audi AG"
                        },
                        new
                        {
                            Id = 10,
                            Abrv = "VW",
                            Name = "Volkswagen"
                        });
                });

            modelBuilder.Entity("Coreapp.Models.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Abrv")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("VehicleModel");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            Abrv = "A-class",
                            MakeId = 2,
                            Name = "A180"
                        },
                        new
                        {
                            Id = 8,
                            Abrv = "A-class",
                            MakeId = 2,
                            Name = "A160"
                        },
                        new
                        {
                            Id = 9,
                            Abrv = "C-class",
                            MakeId = 2,
                            Name = "C43"
                        },
                        new
                        {
                            Id = 10,
                            Abrv = "C-class",
                            MakeId = 2,
                            Name = "C300"
                        },
                        new
                        {
                            Id = 11,
                            Abrv = "GLE",
                            MakeId = 2,
                            Name = "GLE580"
                        },
                        new
                        {
                            Id = 12,
                            Abrv = "GLE",
                            MakeId = 2,
                            Name = "GLE350"
                        },
                        new
                        {
                            Id = 13,
                            Abrv = "GLE",
                            MakeId = 2,
                            Name = "GLE400"
                        },
                        new
                        {
                            Id = 14,
                            Abrv = "M-Class",
                            MakeId = 2,
                            Name = "ML350"
                        },
                        new
                        {
                            Id = 15,
                            Abrv = "M-Class",
                            MakeId = 2,
                            Name = "ML400"
                        },
                        new
                        {
                            Id = 16,
                            Abrv = "i8",
                            MakeId = 1,
                            Name = "i8"
                        },
                        new
                        {
                            Id = 17,
                            Abrv = "Series-3",
                            MakeId = 1,
                            Name = "316"
                        },
                        new
                        {
                            Id = 18,
                            Abrv = "Focus",
                            MakeId = 3,
                            Name = "Focus"
                        },
                        new
                        {
                            Id = 19,
                            Abrv = "Ka",
                            MakeId = 3,
                            Name = "Ka"
                        },
                        new
                        {
                            Id = 20,
                            Abrv = "ix35",
                            MakeId = 4,
                            Name = "ix35"
                        },
                        new
                        {
                            Id = 21,
                            Abrv = "Kona",
                            MakeId = 4,
                            Name = "Kona"
                        },
                        new
                        {
                            Id = 22,
                            Abrv = "3",
                            MakeId = 5,
                            Name = "323"
                        },
                        new
                        {
                            Id = 23,
                            Abrv = "6",
                            MakeId = 5,
                            Name = "6"
                        },
                        new
                        {
                            Id = 24,
                            Abrv = "Cayenne",
                            MakeId = 6,
                            Name = "Cayenne"
                        },
                        new
                        {
                            Id = 25,
                            Abrv = "911",
                            MakeId = 6,
                            Name = "911"
                        },
                        new
                        {
                            Id = 26,
                            Abrv = "Captur",
                            MakeId = 7,
                            Name = "Captur"
                        },
                        new
                        {
                            Id = 27,
                            Abrv = "Scenic",
                            MakeId = 7,
                            Name = "Scenic"
                        },
                        new
                        {
                            Id = 28,
                            Abrv = "Superb",
                            MakeId = 8,
                            Name = "Superb"
                        },
                        new
                        {
                            Id = 29,
                            Abrv = "Octavia",
                            MakeId = 8,
                            Name = "Octavia"
                        },
                        new
                        {
                            Id = 30,
                            Abrv = "A3",
                            MakeId = 9,
                            Name = "A3"
                        },
                        new
                        {
                            Id = 31,
                            Abrv = "A4",
                            MakeId = 9,
                            Name = "A4"
                        },
                        new
                        {
                            Id = 32,
                            Abrv = "Passsat",
                            MakeId = 10,
                            Name = "Passat"
                        },
                        new
                        {
                            Id = 33,
                            Abrv = "Arteon",
                            MakeId = 10,
                            Name = "Arteon"
                        });
                });

            modelBuilder.Entity("Coreapp.Models.VehicleModel", b =>
                {
                    b.HasOne("Coreapp.Models.VehicleMake", "Make")
                        .WithMany("VehicleModels")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("Coreapp.Models.VehicleMake", b =>
                {
                    b.Navigation("VehicleModels");
                });
#pragma warning restore 612, 618
        }
    }
}
